#!/bin/bash

# author: Georg Schmidt <gs-develop@gs-sys.de>
# version: 01.2017

## location: /sbin/updater
# cp updater.sh /sbin/updater
# chmod 0555 /sbin/updater

ps -A | grep updater > /dev/null 2>&1
if [ $? -gt 0 ]; then
   echo "Updater still running! Quit now."
   exit 0
fi

apt update
apt -y dist-upgrade

apt -y autoremove
apt -y autoclean

# store time in log file
echo>>/var/log/updater-gs.log $(date)
