#!/bin/bash

# author: Georg Schmidt <gs-develop@gs-sys.de>
# version: 03.2019

## location: /usr/sbin/updater
# cp updater.sh /usr/sbin/updater
# chmod 0555 /usr/sbin/updater

if [[ $EUID -ne 0 ]]; then
   echo "Updater must be run as root! Quit now."
   exit 1
fi

ps -A | grep updater > /dev/null 2>&1
if [ $? -gt 0 ]; then
   echo "Updater still running! Quit now."
   exit 0
fi

apt update
apt -y dist-upgrade

apt -y autoremove
apt -y autoclean

# store time in log file
echo>>/var/log/updater-gs.log $(date)
