#!/bin/bash

passwordArchiv=1PeNAEMksBswweirp6hb

# link by https://www.gs-sec.de

# plaintext
# wget -O /tmp/openjdk12-gs.tar.gz https://www.gs-sec.de/java12-linux-64.tar.gz

# crypted
wget -O- https://www.gs-sec.de/java12-linux-64.tar.gz.aes | openssl enc -d -camellia-256-cbc -k "$passwordArchiv" -out /tmp/openjdk12-gs.tar.gz

#generate archiv
# openssl enc -camellia-256-cbc -k "$passwordArchiv" -in openjdk12-gs.tar.gz -out /tmp/openjdk12-gs.tar.gz.aes


cd /opt
tar -xvzf /tmp/openjdk12-gs.tar.gz


chown root /opt/openjdk12/public/java12
chmod 555 /opt/openjdk12/public/java12
chown root /opt/openjdk12/public/javac12
chmod 555 /opt/openjdk12/public/javac12
chown root /opt/openjdk12/public/java12fx
chmod 555 /opt/openjdk12/public/java12fx

grep -qF '/opt/openjdk12/public' /etc/environment || sed -i -E 's/\/usr\/local\/sbin/\/usr\/local\/sbin:\/opt\/openjdk12\/public/g' /etc/environment

export PATH=$PATH:/opt/openjdk12/public

echo "install complete!"
java12 --version
exit 0
