#!/bin/bash

wget -c -O /tmp/veracrypt-1.23-setup.tar.bz2 https://launchpad.net/veracrypt/trunk/1.23/+download/veracrypt-1.23-setup.tar.bz2

cd /tmp
# download checksum and test it
wget -O- https://launchpad.net/veracrypt/trunk/1.23/+download/veracrypt-1.23-sha512sum.txt | grep veracrypt-1.23-setup.tar.bz2 | sed -e "s/\r//g" | sha512sum -c -

if [ $? -eq 0 ]
then
	ARCH=`dpkg --print-architecture`
	if [ "$ARCH" == "amd64" ]
	then
	  tar -xvjf /tmp/veracrypt-1.23-setup.tar.bz2 veracrypt-1.23-setup-console-x64
	  ./veracrypt-1.23-setup-console-x64
	else
	  tar -xvjf /tmp/veracrypt-1.23-setup.tar.bz2 veracrypt-1.23-setup-console-x86
	  ./veracrypt-1.23-setup-console-x86
	fi
else
  echo "Checksum was invalid!"
fi

echo "To start VeraCrypt run 'veracrypt' in the terminal!"
echo "install complete!